# Default values for wisp-problems.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: competemcgill/wisp-problems
  tag: "latest"
  pullPolicy: Always

nameOverride: ""
fullnameOverride: "wisp-problems"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  limits:
    cpu: 50m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 100Mi
