version: "3"
services:
  api:
    image: node:11.13.0-alpine
    container_name: api
    environment:
      - NODE_ENV=test
      - DB_URL=mongodb://mongo:27017/wisp
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm i && npm run test:local"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    logging:
      driver: none
    ports:
      - 27017:27017